branches:
  only:
    - master

language: cpp

git:
  depth: 10

cache:
  - ../mysql-5.5


jobs:
  include:
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      python: "3.6"
      before_install:
        - export WDIR=$(pwd)
        - export PATH=~/.local/bin:$WDIR/../clang-9/usrbin:$PATH
        - sudo -i add-apt-repository -y ppa:deadsnakes/ppa
        - sudo -i apt-get -q update
        - sudo -i apt-get -y install python3.6 python3.6-venv
        - sudo -i update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
        - sudo -i sh -c "curl https://bootstrap.pypa.io/get-pip.py | python"
        - sudo -i python -m pip install requests uritemplate discord-webhook
        - if [ ! -d "../clang-9/bin" ]; then (curl -SL https://bitbucket.org/rom4s/other.get/downloads/clang-9.tar.xz | tar -xJC ..); fi
      script: 
        - echo "pwd = $WDIR"
        - python --version; python -m pip --version; pwd;
        - clang++-9 --version; clang-9 --version; echo wow
      cache:
        - ../clang-9

    - name: 'Build on Windows'
      os: windows
      python: "3.8"
      before_install:
        - export WDIR=$(pwd)
        - export PATH=/C/Python38:/C/Python38/Scripts:$PATH
        - if [ ! -d "/C/Python38/Scripts" ]; then (choco install python --version=3.8.0); fi
        - python -m pip install --upgrade pip
        - python -m pip install requests uritemplate discord-webhook
      script:
        - echo "pwd = $WDIR"
        - powershell '.\windows_run.bat'
      cache:
        - /C/Python38