branches:
  only:
    - master

sudo: required

git:
  depth: 10

matrix:
  include:
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      language: cpp
      python: "3.4"
      before_install:
        - export WDIR=$(pwd)
        - export PATH=~/.local/bin:$WDIR/clang9:$PATH
        - sudo apt-get -q update
        - sudo apt-get -y install python3 python3-pip
        - sudo python3 -m pip install requests uritemplate discord-webhook
        - alias python=python3

    - name: 'Build on Windows'
      os: windows
      language: cpp
      python: "3.7"
      before_install:
        - choco install python --version=3.7.0
        - export PATH=/C/Python38:$PATH
        - /C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Auxiliary/Build/vcvars32.bat


script: python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd; cl; echo 'ok?'