branches:
  only:
    - master

git:
  depth: 10

matrix:
  include:
    - os : linux
      dist: trusty
      language: cpp
      python: "3.6"

    - os : windows
      language : cpp
      before_install:
        - choco install python --version=3.8.0
        - export PATH=/C/Python38:$PATH
        - SET


script: python3 --version || python --version