branches:
  only:
    - master

git:
  depth: 10

matrix:
  include:
    - os : linux
      dist: trusty
      language: cpp
      python: "3.6"

    - os : windows
      language : shell
      python: "3.6"

script: python3 --version