branches:
  only:
    - master

sudo: required

git:
  depth: 10

matrix:
  include:
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      language: cpp
      python: "3.6"
      before_install:
        - alias python=python3

    - name: 'Build on Windows'
      os: windows
      language: cpp
      python: "3.6"
      before_install:
        - choco install python --version=3.6.0
        - export PATH=/C/Python38:$PATH
        - ls -la '/C/Program Files (x86)/Microsoft Visual Studio/'


script: python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd; cl; echo 'ok?'