branches:
  only:
    - master

git:
  depth: 10

matrix:
  include:
    - os : linux
      language: cpp
      python: "3.6"

    - os : windows
      language : cpp
      python: "3.6"

script: python3 --version && pip3 --version