branches:
  only:
    - master

sudo: required

git:
  depth: 10

matrix:
  include:
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      language: cpp
      python: "3.7"
      before_install:
        - sudo add-apt-repository -y ppa:deadsnakes/ppa
        - sudo apt-get -q update
        - sudo apt-get -y install python3 python3-pip
        - sudo python3 -m pip install requests uritemplate discord-webhook
        - alias python=python3

    - name: 'Build on Windows'
      os: windows
      language: cpp
      python: "3.7"
      before_install:
        - choco install python --version=3.7.0
        - export PATH=/C/Python38:$PATH
        - cmd /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86 && echo "loaded!"'
        # - ls -la '/C/Program Files (x86)/Microsoft Visual Studio/'


script: python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd; cl; echo 'ok?'