branches:
  only:
    - master

language: cpp

git:
  depth: 10

jobs:
  include:
    - name: 'Build on Linux (Ubuntu 14.04)'
      os: linux
      dist: trusty
      python: "3.6"
      before_install:
        - export WDIR=$(pwd)
        - export PATH=~/.local/bin:$WDIR/clang9:$PATH
        - sudo -i add-apt-repository -y ppa:deadsnakes/ppa
        - sudo -i apt-get -q update
        - sudo -i apt-get -y install python3.6 python3.6-venv
        - sudo -i sh -c "curl https://bootstrap.pypa.io/get-pip.py | python3.6"
        - sudo -i python3.6 -m pip install requests uritemplate discord-webhook
        - sudo -i update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
      script: python3.6 --version; python --version; python3.6 -m pip --version; python -m pip --version; echo ~; ls; pwd;

    - name: 'Build on Windows'
      os: windows
      python: "3.8"
      before_install:
        - export WDIR=$(pwd)
        - choco install python --version=3.8.0
        - export PATH=/C/Python38:$PATH
      script:
        - echo "pwd = " pwd
        - powershell '.\windows_run.bat'
        - echo 'ok?'
        - python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd;

# script: python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd; cl; echo 'ok?'