branches:
  only:
    - master

sudo: required

git:
  depth: 10

matrix:
  include:
    - os : linux
      dist: trusty
      language: cpp
      python: "3.6"
      before_install:
        - alias python=python3

    - os : windows
      language : cpp
      before_install:
        - choco install python --version=3.6.0
        - export PATH=/C/Python38:$PATH
        - alias python=python3
        - cl; echo 'ok?'


script: python3 --version; python --version; pip3 --version; pip --version; echo ~; ls; pwd